filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.json
  json.keys_under_root: true
  json.add_error_key: true

setup.ilm.enabled: false                   # вимикаємо ILM, щоб не створювався дефолтний alias filebeat-*
setup.template.enabled: true               # увімкнути кастомний шаблон
setup.template.name: "suricata"            # назва шаблону
setup.template.pattern: "suricata-*"       # на який індекс цей шаблон поширюється

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "suricata-%{+yyyy.MM.dd}"         # індекси виду suricata-2025.05.26
